# Generated by Django 5.0.6 on 2024-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('cog', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('grupo', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
