# Generated by Django 5.0.6 on 2024-10-22 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_cog_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('numero_control', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='ProductoLPN',
            fields=[
                ('id_producto_lpn', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.estado')),
                ('id_personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.personal')),
            ],
            options={
                'db_table': 'productolpn',
            },
        ),
        migrations.CreateModel(
            name='ProductoSKU',
            fields=[
                ('id_producto_sku', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria')),
            ],
            options={
                'db_table': 'productosku',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_transaccion',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Actualización', 'Actualización')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('historial', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('eje1', models.CharField(blank=True, max_length=100, null=True)),
                ('eje2', models.CharField(blank=True, max_length=100, null=True)),
                ('eje3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Responsable', 'Responsable'), ('Usuario', 'Usuario')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50)),
                ('id_perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.perfil')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='productolpn',
            name='id_producto_sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productosku'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_producto_sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productosku'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_producto_lpn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productolpn'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_tipo_transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.tipotransaccion'),
        ),
        migrations.AddField(
            model_name='productolpn',
            name='id_ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.ubicacion'),
        ),
    ]
